id: P000773
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:02:19.548091
source_metadata:
  id: bdr:W913
  title: འདུལ་བའི་ཆོས་འབྱུང
  author: ''
  volumes:
    7f5acdc4aa824d7fb8b53c662aa12842:
      image_group_id: I00KG09702
      title: ''
      volume_number: 1
      total_pages: 74
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
