id: I46F5CFD7
legacy_id: P000773
ocr_import_info:
  bdrc_scan_id: W913
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T20:30:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T05:06:20.992205+00:00'
last_modified: 2022-09-04 13:06:26.348810
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W913
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW913
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བའི་ཆོས་འབྱུང་།
  author: པཎ་ཆེན་བསོད་ནམས་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9037444285800739
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I00KG09702:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG09702
      total_pages: 74
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG09702.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.9037444285800739
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
